# 공통 설정 (데이터 경로 및 공통 하이퍼파라미터)
common:
  vocab_path: "vocab_3.pkl"
  train_img_dir: "./data/images/train"
  train_json: "./data/captions/train_3.json"
  val_img_dir: "./data/images/val"
  val_json: "./data/captions/val_3.json"
  checkpoint_dir: "./checkpoints"

# CNN-RNN 모델 설정
cnn_rnn:
  model_name: "cnn_rnn"
  encoder_type: "resnet18" # 학습 시 여기서 모델 결정 ("resnet18" 또는 "mobilenet_v2")
  epochs: 30
  batch_size: 64
  learning_rate: 0.00014
  num_workers: 8
  
  # 모델별 상세 파라미터 (코드에서 encoder_type에 따라 자동 선택)
  params:
    resnet18:
      embed_size: 512
      hidden_size: 512
      num_layers: 1
    mobilenet_v2:
      embed_size: 300
      hidden_size: 512
      num_layers: 1

# ViT-GPT2 모델 설정
vit_gpt2:
  model_name: "vit_gpt2"
  embed_size: 768
  hidden_size: 1024
  num_layers: 6
  epochs: 10
  batch_size: 32
  learning_rate: 0.00001
  num_workers: 4