_wandb:
    value:
        cli_version: 0.24.0
        e:
            4tzz3d6f8sj958flj4ni0g5i3qg0cof5:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "6442450944"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "226096762880"
                email: kjink9921@gmail.com
                executable: /Users/daniel/project/myenv/bin/python
                git:
                    commit: a21b7825ede7d60f344a90af8cf2d2f7a6183d38
                    remote: https://github.com/jink221/super_teamproject2.git
                host: Jinkyuui-MacBookPro.local
                memory:
                    total: "25769803776"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/daniel/project/train.py
                python: CPython 3.9.6
                root: /Users/daniel/project
                startedAt: "2026-01-18T13:53:04.828413Z"
                writerId: 4tzz3d6f8sj958flj4ni0g5i3qg0cof5
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.9.6
            "5": 0.24.0
            "8":
                - 2
            "12": 0.24.0
            "13": darwin-arm64
batch_size:
    value: 64
decoder_type:
    value: lstm
embed_size:
    value: 512
encoder_type:
    value: resnet18
epochs:
    value: 30
hidden_size:
    value: 512
image_size:
    value:
        - 224
        - 224
learning_rate:
    value: 0.00014
norm_mean:
    value:
        - 0.485
        - 0.456
        - 0.406
norm_std:
    value:
        - 0.229
        - 0.224
        - 0.225
num_layers:
    value: 1
num_workers:
    value: 8
optimizer_type:
    value: AdamW
save_base_dir:
    value: ./checkpoints
shuffle:
    value: true
train_img_dir:
    value: ./data/images/train
train_json:
    value: ./data/captions/train_3.json
val_img_dir:
    value: ./data/images/val
val_json:
    value: ./data/captions/val_3.json
vocab_path:
    value: vocab_3.pkl
