_wandb:
    value:
        cli_version: 0.23.1
        e:
            plxaku1ayskgm1sfuxp6lugn2cdwd9bg:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                    swapTotalBytes: "4294967296"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "216090075136"
                email: kjink9921@gmail.com
                executable: /Users/daniel/team_project/myenv/bin/python
                git:
                    commit: 94533e911cf5a5f52c42bde3c1872d4ec1e565fc
                    remote: https://github.com/jink221/git_demo_.git
                host: Jinkyuui-MacBookPro.local
                memory:
                    total: "25769803776"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/daniel/team_project/train.py
                python: CPython 3.9.6
                root: /Users/daniel/team_project
                startedAt: "2026-01-12T00:38:15.129765Z"
                writerId: plxaku1ayskgm1sfuxp6lugn2cdwd9bg
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.9.6
            "5": 0.23.1
            "8":
                - 2
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 64
decoder_type:
    value: lstm
embed_size:
    value: 300
encoder_type:
    value: mobilenet_v2
epochs:
    value: 30
hidden_size:
    value: 512
image_size:
    value:
        - 224
        - 224
learning_rate:
    value: 0.00014
norm_mean:
    value:
        - 0.485
        - 0.456
        - 0.406
norm_std:
    value:
        - 0.229
        - 0.224
        - 0.225
num_layers:
    value: 1
num_workers:
    value: 8
optimizer_type:
    value: AdamW
save_base_dir:
    value: ./checkpoints
shuffle:
    value: true
train_img_dir:
    value: ./data/images/train
train_json:
    value: ./data/captions/train_3.json
val_img_dir:
    value: ./data/images/val
val_json:
    value: ./data/captions/val_3.json
vocab_path:
    value: vocab_3.pkl
